
compiler_type = "ido"

compiler_command = "python3 ./tools/asm-processor/build.py tools/ido5.3/cc -- mips-linux-gnu-as -mips3 -march vr4300 -I include -- -Xcpluscomm -O2 -mips2 -Olimit 2000 -I include -I include/libultra -I include/libultra/PR -DTARGET_N64 -D_FINALROM -DF3DEX_GBI -DNDEBUG -non_shared -c -Wab,-r4300_mul -G 0"
assembler_command = "mips-linux-gnu-as -mips3 -march vr4300 -I include"

[preserve_macros]
"_*gs?[DS]P.*" = "void"
"gs?Dma.*" = "void"
"gs?Imm.*" = "void"
"gs?MoveWd.*" = "void"
"gSetImage" = "void"
"MAX" = "void"
"MIN" = "void"
"GCCc0w0" = "void"
"GCCc0w1" = "void"
"GCCc1w0" = "void"
"GCCc1w1" = "void"
"CALC_DXT" = "void"
"GBL_.*" = "void"
"_SHIFTL" = "void"
"_SHIFTR" = "void"
"RM_.*" = "void"
OVERRIDE_FLAG_CHECK = "int"
OS_K0_TO_PHYSICAL = "int"
"G_.*" = "int"
"TEXEL.*" = "int"
"PRIMITIVE" = "int"
"BOWTIE_VAL" = "int"
"ALPHA_CVG_SEL" = "int"
"ZMODE_OPA" = "int"
"TEX_EDGE" = "int"
"LIGHT_*." = "int"
"FORCE_BL" = "int"
"CVG_DST_FULL" = "int"
"CVG_X_ALPHA" = "int"

[decompme.compilers]
"ido5.3/cc" = "ido5.3"